### ISSUE TITLE
Chinese version of visiting child clusters with rbac

### ISSUE THREAD

**Issue by dixudx** [clusternet/website#11]
翻译源: https://github.com/clusternet/website/blob/main/content/en/docs/tutorials/cluster-management/visiting-child-clusters-with-rbac/
翻译后: `content/zh-cn/docs/tutorials/cluster-management/visiting-child-clusters-with-rbac/`

**Comment by MentosL** [comment]
pls assign me

**Comment by MentosL** [comment]
already translate，pls check it #34
