### ISSUE TITLE
Chinese version of deploying applications to multiple clusters

### ISSUE THREAD

**Issue by dixudx** [clusternet/website#9]
翻译源: https://github.com/clusternet/website/blob/main/content/en/docs/tutorials/deploy-to-multiple-clusters.md
翻译后: `content/zh-cn/docs/tutorials/deploy-to-multiple-clusters.md`

**Comment by MentosL** [comment]
please  assign me

**Comment by MentosL** [comment]
pls check  #19

**Comment by Xlight5** [comment]
Clusternet文档
此存储库包含用于构建托管在https://clusternet.io/的 Clusternet 网站的资产。

要求
[使用netlify.toml](https://github.com/clusternet/website/blob/main/netlify.toml)中指定的版本安装[Hugo（扩展版）](https://gohugo.io/getting-started/installing)

入门
1. 克隆这个 repo 及其子模块
git clone https://github.com/clusternet/website.git
cd website
make load-submodule
2.在本地服务站点
make serve
[更改将在http://localhost:1313](http://localhost:1313/)实时刷新

修改文档
英语：content/en/documentation
资产：文档中的附加图像应放在文件夹中static。
每个 PR 都会触发 Netlify 构建一个预览站点。合并到main分支后，站点https://clusternet.io/将由 Netlify 自动发布。
